### ISSUE TITLE
Delayed Response on Pedal Press

### ISSUE THREAD

**Issue by TheRevenantStar** [DDRBoxman/picodeck#4]
After setting up the device in the StreamDeck settings, there is a 3 second delay from pressing a pedal and the software responding.
When the action does occur, it works exactly as configured, it just lags considerably no matter if it's press down, release, or just click.

Using an M1 mac, MacOS 12.4, StreamDeck version 5.2.1

**Comment by DDRBoxman** [comment]
Might be worth increasing the hid report time here just to send less messages, this should really only send on changes but I got lazy.

https://github.com/DDRBoxman/picodeck/blob/fd1e844799a28e37ecdf220443832c80ea7d0c6c/src/main.c#L130

**Comment by TheRevenantStar** [comment]
That seems to have fixed it, I bumped it to 500ms.
