### ISSUE TITLE
Streamdeck XL Support?

### ISSUE THREAD

**Issue by WitoTV** [DDRBoxman/picodeck#5]
Is there some possibility of an extension of this so it presents itself as streamdeck XL? I don't know a lot about raspberry pi pico but if we could wirelessly send data to an android device via Bluetooth or just straight-up websockets maybe we could have a custom app there to display stuff and pass "click" events. aka. pico acting as a relay between PC and Android app.

I sadly myself lack knowledge about C and HID to perform this so this is mostly a question of interest.

(I would have not used issues but I was not able to find other way of contact)

**Comment by DDRBoxman** [comment]
From my experiments running the pico as a StreamDeck XL or even a regular StreamDeck will overwhelm the usb stack when the software sends down the data for the button images. I do have plans in the future to look into seeing if the Pi zero can handle this by implementing a custom usb gadget.

**Comment by WitoTV** [comment]
Yea good point. I will wait then for some possible updates (new project, repo, etc) on the topic. Thank you.
